import Link from 'next/link';
import { notFound } from 'next/navigation';
import PrintButton from '@/components/ui/PrintButton';
import { getPurchaseById } from '@/app/actions/purchases';

export default async function PurchaseInvoice({ params }: { params: Promise<{ id: string; purchaseId: string }> }) {
  const { id, purchaseId } = await params;
  const purchase: any = await getPurchaseById(purchaseId);
  if (!purchase || purchase.supplier_id !== id) notFound();
  return <div style={{ maxWidth: 850, margin: '0 auto', padding: 30 }}><div className="d-flex gap-2 justify-content-center mb-4"><PrintButton /><Link href={`/suppliers/${id}/purchases`} className="btn btn-added">Back to purchases</Link></div><div className="card"><div className="card-body p-4"><div className="d-flex justify-content-between border-bottom pb-3 mb-4"><div><h2 className="mb-1">PURCHASE INVOICE</h2><div className="text-muted">{purchase.purchase_number}</div></div><div className="text-end"><strong>{purchase.supplier?.name}</strong><br />{purchase.supplier?.phone}<br />{purchase.supplier?.address}</div></div><div className="d-flex justify-content-between align-items-center mb-3"><div>Purchased by: <strong>{purchase.created_by_name || 'Unknown'}</strong></div><div>Date: <strong>{new Date(purchase.created_at).toLocaleString()}</strong></div></div><table className="table"><thead><tr><th>Product</th><th>Variant</th><th className="text-end">Quantity</th><th className="text-end">Unit Cost</th><th className="text-end">Total</th></tr></thead><tbody>{purchase.items.map((item: any) => <tr key={item.id}><td>{item.variant?.product?.name || 'Unknown product'}</td><td>{item.variant?.variant_name || 'Default'}</td><td className="text-end">{Number(item.quantity)}</td><td className="text-end">Rs. {Number(item.unit_cost).toFixed(2)}</td><td className="text-end">Rs. {Number(item.total).toFixed(2)}</td></tr>)}</tbody></table><div className="ms-auto" style={{ maxWidth: 300 }}><div className="d-flex justify-content-between"><span>Subtotal:</span><strong>Rs. {Number(purchase.subtotal || 0).toFixed(2)}</strong></div><div className="border-top mt-2 pt-2">{(Number(purchase.shipping_price || 0) + Number(purchase.loader_price || 0) + Number(purchase.unloading_price || 0)) > 0 && <div className="d-flex justify-content-between"><span><strong>Shipping charges:</strong></span><strong>Rs. {(Number(purchase.shipping_price || 0) + Number(purchase.loader_price || 0) + Number(purchase.unloading_price || 0)).toFixed(2)}</strong></div>}</div><div className="d-flex justify-content-between border-top mt-3 pt-2"><span><strong>Total Amount:</strong></span><strong>Rs. {Number(purchase.total_amount).toFixed(2)}</strong></div><div className="d-flex justify-content-between"><span>Paid now:</span><span>Rs. {Number(purchase.paid_amount).toFixed(2)}</span></div><div className="d-flex justify-content-between border-top mt-2 pt-2"><span>Remaining amount:</span><strong>Rs. {Number(purchase.remaining_amount).toFixed(2)}</strong></div></div>{purchase.notes && <div className="mt-4"><strong>Notes:</strong> {purchase.notes}</div>}</div></div></div>;
}
